version: '2.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"

  fluent-bit:
    image: fluent/fluent-bit:1.7.9
    volumes:
      - ./fluent-bit/conf:/fluent-bit/etc
    links:
      - elasticsearch
    ports:
      - 24224:24224
      #- 5140:5140/udp
      #- 2020:2020
    depends_on:
      - elasticsearch
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24

